/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShamirInputs: typeof import('./src/components/ShamirInputs.vue')['default']
    SharesModal: typeof import('./src/components/SharesModal.vue')['default']
    StepGenerateMasterKey: typeof import('./src/components/setup/StepGenerateMasterKey.vue')['default']
    StepWelcome: typeof import('./src/components/setup/StepWelcome.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
