// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * AddMemberToGroupRequest
 */
export type AddMemberToGroupRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * AddMemberToGroupResponse
 */
export type AddMemberToGroupResponse = {
    /**
     * Group Id
     */
    group_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * AddOwnerToGroupRequest
 */
export type AddOwnerToGroupRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * AddOwnerToGroupResponse
 */
export type AddOwnerToGroupResponse = {
    /**
     * Group Id
     */
    group_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * AdminLoginRequest
 */
export type AdminLoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * AdminLoginResponse
 */
export type AdminLoginResponse = {
    /**
     * Admin Id
     */
    admin_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Message
     */
    message: string;
};

/**
 * ConfigureSsoProviderRequest
 *
 * Configure SSO provider with OpenID Connect auto-discovery.
 */
export type ConfigureSsoProviderRequest = {
    /**
     * Client Id
     *
     * Client ID OAuth2
     */
    client_id: string;
    /**
     * Client Secret
     *
     * Client secret OAuth2
     */
    client_secret: string;
    /**
     * Discovery Url
     *
     * OpenID Connect discovery URL (.well-known/openid_configuration)
     */
    discovery_url: string;
};

/**
 * CreateGroupRequest
 */
export type CreateGroupRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * CreateGroupResponse
 */
export type CreateGroupResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Message
     */
    message: string;
};

/**
 * CreatePasswordRequest
 */
export type CreatePasswordRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder?: string | null;
    /**
     * Group Id
     */
    group_id: string;
};

/**
 * CreatePasswordResponse
 */
export type CreatePasswordResponse = {
    /**
     * Id
     */
    id: string;
};

/**
 * CreateUserRequest
 */
export type CreateUserRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * CreateUserResponse
 */
export type CreateUserResponse = {
    /**
     * Id
     */
    id: string;
};

/**
 * CreateVaultPostRequest
 */
export type CreateVaultPostRequest = {
    /**
     * Nb Shares
     */
    nb_shares: number;
    /**
     * Threshold
     */
    threshold: number;
};

/**
 * CreateVaultPostResponse
 */
export type CreateVaultPostResponse = {
    /**
     * Setup Id
     */
    setup_id: string;
    /**
     * Shares
     */
    shares: Array<ShareResponse>;
};

/**
 * EventData
 */
export type EventData = {
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Occurred On
     */
    occurred_on: string;
    /**
     * Priority
     */
    priority: string;
};

/**
 * GetGroupResponse
 */
export type GetGroupResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is Personal
     */
    is_personal: boolean;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Owners
     */
    owners: Array<string>;
    /**
     * Members
     */
    members: Array<string>;
};

/**
 * GetPasswordListResponse
 */
export type GetPasswordListResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Folder
     */
    folder: string;
    /**
     * Group Id
     */
    group_id: string;
};

/**
 * GetPasswordResponse
 */
export type GetPasswordResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Folder
     */
    folder: string;
};

/**
 * GetUserMeResponse
 */
export type GetUserMeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Roles
     */
    roles: Array<string>;
    /**
     * Personal Group Id
     */
    personal_group_id?: string | null;
};

/**
 * GetUserResponse
 */
export type GetUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Roles
     */
    roles?: Array<string>;
};

/**
 * GroupAccessItem
 */
export type GroupAccessItem = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Permissions
     */
    permissions: Array<PermissionEnum>;
    /**
     * Is Owner
     */
    is_owner: boolean;
};

/**
 * GroupItem
 */
export type GroupItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is Personal
     */
    is_personal: boolean;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Owners
     */
    owners: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IsSsoConfigSetResponse
 *
 * Response indicating if SSO is configured.
 */
export type IsSsoConfigSetResponse = {
    /**
     * Is Set
     */
    is_set: boolean;
};

/**
 * ListEventsResponse
 */
export type ListEventsResponse = {
    /**
     * Events
     */
    events: Array<EventData>;
};

/**
 * ListGroupsResponse
 */
export type ListGroupsResponse = {
    /**
     * Groups
     */
    groups: Array<GroupItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * ListPasswordAccessResponse
 */
export type ListPasswordAccessResponse = {
    /**
     * Resource Id
     */
    resource_id: string;
    /**
     * User Access List
     */
    user_access_list: Array<UserAccessItem>;
    /**
     * Group Access List
     */
    group_access_list: Array<GroupAccessItem>;
};

/**
 * ListUserResponse
 */
export type ListUserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Roles
     */
    roles: Array<string>;
};

/**
 * LockVaultPostResponse
 */
export type LockVaultPostResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * PermissionEnum
 */
export type PermissionEnum = 'read';

/**
 * RefreshAccessTokenResponse
 */
export type RefreshAccessTokenResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * RegisterAdminRequest
 */
export type RegisterAdminRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name: string;
};

/**
 * RegisterAdminResponse
 */
export type RegisterAdminResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Message
     */
    message: string;
};

/**
 * RemoveMemberFromGroupResponse
 */
export type RemoveMemberFromGroupResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * SharePasswordRequest
 */
export type SharePasswordRequest = {
    /**
     * Group Id
     */
    group_id: string;
};

/**
 * SharePasswordResponse
 */
export type SharePasswordResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ShareResponse
 */
export type ShareResponse = {
    /**
     * Secret
     */
    secret: string;
};

/**
 * SsoCallbackResponse
 */
export type SsoCallbackResponse = {
    /**
     * Message
     */
    message: string;
    user: SsoUserInfo;
};

/**
 * SsoUserInfo
 */
export type SsoUserInfo = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Is New User
     */
    is_new_user: boolean;
};

/**
 * UnlockVaultPostRequest
 */
export type UnlockVaultPostRequest = {
    /**
     * Shares
     *
     * List of share secrets (hex strings with embedded index)
     */
    shares: Array<string>;
};

/**
 * UnlockVaultPostResponse
 */
export type UnlockVaultPostResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * UpdateGroupRequest
 */
export type UpdateGroupRequest = {
    /**
     * Name
     */
    name: string;
};

/**
 * UpdateGroupResponse
 */
export type UpdateGroupResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Message
     */
    message: string;
};

/**
 * UpdatePasswordRequest
 */
export type UpdatePasswordRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Folder
     */
    folder?: string | null;
};

/**
 * UpdateUserRequest
 */
export type UpdateUserRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
};

/**
 * UserAccessItem
 */
export type UserAccessItem = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Permissions
     */
    permissions: Array<PermissionEnum>;
    /**
     * Is Owner
     */
    is_owner: boolean;
};

/**
 * ValidateSetupRequest
 */
export type ValidateSetupRequest = {
    /**
     * Setup Id
     */
    setup_id: string;
};

/**
 * ValidateSetupResponse
 */
export type ValidateSetupResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VaultStatus
 */
export type VaultStatus = 'LOCKED' | 'UNLOCKED' | 'NOT_SETUP' | 'PENDING' | 'SETUPED';

/**
 * VaultStatusResponse
 */
export type VaultStatusResponse = {
    status: VaultStatus;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateVaultApiVaultSetupPostData = {
    body: CreateVaultPostRequest;
    path?: never;
    query?: never;
    url: '/api/vault/setup';
};

export type CreateVaultApiVaultSetupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVaultApiVaultSetupPostError = CreateVaultApiVaultSetupPostErrors[keyof CreateVaultApiVaultSetupPostErrors];

export type CreateVaultApiVaultSetupPostResponses = {
    /**
     * Successful Response
     */
    201: CreateVaultPostResponse;
};

export type CreateVaultApiVaultSetupPostResponse = CreateVaultApiVaultSetupPostResponses[keyof CreateVaultApiVaultSetupPostResponses];

export type ValidateVaultSetupApiVaultValidateSetupPostData = {
    body: ValidateSetupRequest;
    path?: never;
    query?: never;
    url: '/api/vault/validate-setup';
};

export type ValidateVaultSetupApiVaultValidateSetupPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ValidateVaultSetupApiVaultValidateSetupPostError = ValidateVaultSetupApiVaultValidateSetupPostErrors[keyof ValidateVaultSetupApiVaultValidateSetupPostErrors];

export type ValidateVaultSetupApiVaultValidateSetupPostResponses = {
    /**
     * Successful Response
     */
    200: ValidateSetupResponse;
};

export type ValidateVaultSetupApiVaultValidateSetupPostResponse = ValidateVaultSetupApiVaultValidateSetupPostResponses[keyof ValidateVaultSetupApiVaultValidateSetupPostResponses];

export type UnlockVaultApiVaultUnlockPostData = {
    body: UnlockVaultPostRequest;
    path?: never;
    query?: never;
    url: '/api/vault/unlock';
};

export type UnlockVaultApiVaultUnlockPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlockVaultApiVaultUnlockPostError = UnlockVaultApiVaultUnlockPostErrors[keyof UnlockVaultApiVaultUnlockPostErrors];

export type UnlockVaultApiVaultUnlockPostResponses = {
    /**
     * Successful Response
     */
    200: UnlockVaultPostResponse;
};

export type UnlockVaultApiVaultUnlockPostResponse = UnlockVaultApiVaultUnlockPostResponses[keyof UnlockVaultApiVaultUnlockPostResponses];

export type LockVaultApiVaultLockPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vault/lock';
};

export type LockVaultApiVaultLockPostResponses = {
    /**
     * Successful Response
     */
    200: LockVaultPostResponse;
};

export type LockVaultApiVaultLockPostResponse = LockVaultApiVaultLockPostResponses[keyof LockVaultApiVaultLockPostResponses];

export type GetVaultStatusApiVaultStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vault/status';
};

export type GetVaultStatusApiVaultStatusGetResponses = {
    /**
     * Successful Response
     */
    200: VaultStatusResponse;
};

export type GetVaultStatusApiVaultStatusGetResponse = GetVaultStatusApiVaultStatusGetResponses[keyof GetVaultStatusApiVaultStatusGetResponses];

export type CreatePasswordApiPasswordsPostData = {
    body: CreatePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/passwords/';
};

export type CreatePasswordApiPasswordsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePasswordApiPasswordsPostError = CreatePasswordApiPasswordsPostErrors[keyof CreatePasswordApiPasswordsPostErrors];

export type CreatePasswordApiPasswordsPostResponses = {
    /**
     * Successful Response
     */
    201: CreatePasswordResponse;
};

export type CreatePasswordApiPasswordsPostResponse = CreatePasswordApiPasswordsPostResponses[keyof CreatePasswordApiPasswordsPostResponses];

export type ListPasswordsApiPasswordsListGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Folder
         */
        folder?: string | null;
    };
    url: '/api/passwords/list';
};

export type ListPasswordsApiPasswordsListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPasswordsApiPasswordsListGetError = ListPasswordsApiPasswordsListGetErrors[keyof ListPasswordsApiPasswordsListGetErrors];

export type ListPasswordsApiPasswordsListGetResponses = {
    /**
     * Response List Passwords Api Passwords List Get
     *
     * Successful Response
     */
    200: Array<GetPasswordListResponse>;
};

export type ListPasswordsApiPasswordsListGetResponse = ListPasswordsApiPasswordsListGetResponses[keyof ListPasswordsApiPasswordsListGetResponses];

export type DeletePasswordApiPasswordsPasswordIdDeleteData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/api/passwords/{password_id}';
};

export type DeletePasswordApiPasswordsPasswordIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePasswordApiPasswordsPasswordIdDeleteError = DeletePasswordApiPasswordsPasswordIdDeleteErrors[keyof DeletePasswordApiPasswordsPasswordIdDeleteErrors];

export type DeletePasswordApiPasswordsPasswordIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePasswordApiPasswordsPasswordIdDeleteResponse = DeletePasswordApiPasswordsPasswordIdDeleteResponses[keyof DeletePasswordApiPasswordsPasswordIdDeleteResponses];

export type GetPasswordApiPasswordsPasswordIdGetData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/api/passwords/{password_id}';
};

export type GetPasswordApiPasswordsPasswordIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPasswordApiPasswordsPasswordIdGetError = GetPasswordApiPasswordsPasswordIdGetErrors[keyof GetPasswordApiPasswordsPasswordIdGetErrors];

export type GetPasswordApiPasswordsPasswordIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetPasswordResponse;
};

export type GetPasswordApiPasswordsPasswordIdGetResponse = GetPasswordApiPasswordsPasswordIdGetResponses[keyof GetPasswordApiPasswordsPasswordIdGetResponses];

export type UpdatePasswordApiPasswordsPasswordIdPutData = {
    body: UpdatePasswordRequest;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/api/passwords/{password_id}';
};

export type UpdatePasswordApiPasswordsPasswordIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordApiPasswordsPasswordIdPutError = UpdatePasswordApiPasswordsPasswordIdPutErrors[keyof UpdatePasswordApiPasswordsPasswordIdPutErrors];

export type UpdatePasswordApiPasswordsPasswordIdPutResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type SharePasswordApiPasswordsPasswordIdSharePostData = {
    body: SharePasswordRequest;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/api/passwords/{password_id}/share';
};

export type SharePasswordApiPasswordsPasswordIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SharePasswordApiPasswordsPasswordIdSharePostError = SharePasswordApiPasswordsPasswordIdSharePostErrors[keyof SharePasswordApiPasswordsPasswordIdSharePostErrors];

export type SharePasswordApiPasswordsPasswordIdSharePostResponses = {
    /**
     * Successful Response
     */
    201: SharePasswordResponse;
};

export type SharePasswordApiPasswordsPasswordIdSharePostResponse = SharePasswordApiPasswordsPasswordIdSharePostResponses[keyof SharePasswordApiPasswordsPasswordIdSharePostResponses];

export type UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/passwords/{password_id}/share/{group_id}';
};

export type UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteError = UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteErrors[keyof UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteErrors];

export type UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteResponse = UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteResponses[keyof UnsharePasswordApiPasswordsPasswordIdShareGroupIdDeleteResponses];

export type ListPasswordAccessApiPasswordsPasswordIdAccessGetData = {
    body?: never;
    path: {
        /**
         * Password Id
         */
        password_id: string;
    };
    query?: never;
    url: '/api/passwords/{password_id}/access';
};

export type ListPasswordAccessApiPasswordsPasswordIdAccessGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPasswordAccessApiPasswordsPasswordIdAccessGetError = ListPasswordAccessApiPasswordsPasswordIdAccessGetErrors[keyof ListPasswordAccessApiPasswordsPasswordIdAccessGetErrors];

export type ListPasswordAccessApiPasswordsPasswordIdAccessGetResponses = {
    /**
     * Successful Response
     */
    200: ListPasswordAccessResponse;
};

export type ListPasswordAccessApiPasswordsPasswordIdAccessGetResponse = ListPasswordAccessApiPasswordsPasswordIdAccessGetResponses[keyof ListPasswordAccessApiPasswordsPasswordIdAccessGetResponses];

export type GetUserMeApiUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetUserMeApiUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: GetUserMeResponse;
};

export type GetUserMeApiUsersMeGetResponse = GetUserMeApiUsersMeGetResponses[keyof GetUserMeApiUsersMeGetResponses];

export type DeleteUserApiUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type DeleteUserApiUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiUsersUserIdDeleteError = DeleteUserApiUsersUserIdDeleteErrors[keyof DeleteUserApiUsersUserIdDeleteErrors];

export type DeleteUserApiUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserApiUsersUserIdDeleteResponse = DeleteUserApiUsersUserIdDeleteResponses[keyof DeleteUserApiUsersUserIdDeleteResponses];

export type GetUserApiUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type GetUserApiUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiUsersUserIdGetError = GetUserApiUsersUserIdGetErrors[keyof GetUserApiUsersUserIdGetErrors];

export type GetUserApiUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetUserResponse;
};

export type GetUserApiUsersUserIdGetResponse = GetUserApiUsersUserIdGetResponses[keyof GetUserApiUsersUserIdGetResponses];

export type UpdateUserApiUsersUserIdPutData = {
    body: UpdateUserRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UpdateUserApiUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiUsersUserIdPutError = UpdateUserApiUsersUserIdPutErrors[keyof UpdateUserApiUsersUserIdPutErrors];

export type UpdateUserApiUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type ListUsersApiUsersGetResponses = {
    /**
     * Response List Users Api Users  Get
     *
     * Successful Response
     */
    200: Array<ListUserResponse>;
};

export type ListUsersApiUsersGetResponse = ListUsersApiUsersGetResponses[keyof ListUsersApiUsersGetResponses];

export type CreateUserApiUsersPostData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type CreateUserApiUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiUsersPostError = CreateUserApiUsersPostErrors[keyof CreateUserApiUsersPostErrors];

export type CreateUserApiUsersPostResponses = {
    /**
     * Successful Response
     */
    201: CreateUserResponse;
};

export type CreateUserApiUsersPostResponse = CreateUserApiUsersPostResponses[keyof CreateUserApiUsersPostResponses];

export type PromoteUserToAdminApiUsersUserIdPromoteAdminPostData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/promote-admin';
};

export type PromoteUserToAdminApiUsersUserIdPromoteAdminPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PromoteUserToAdminApiUsersUserIdPromoteAdminPostError = PromoteUserToAdminApiUsersUserIdPromoteAdminPostErrors[keyof PromoteUserToAdminApiUsersUserIdPromoteAdminPostErrors];

export type PromoteUserToAdminApiUsersUserIdPromoteAdminPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type PromoteUserToAdminApiUsersUserIdPromoteAdminPostResponse = PromoteUserToAdminApiUsersUserIdPromoteAdminPostResponses[keyof PromoteUserToAdminApiUsersUserIdPromoteAdminPostResponses];

export type AdminLoginApiAuthLoginPostData = {
    body: AdminLoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AdminLoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AdminLoginApiAuthLoginPostError = AdminLoginApiAuthLoginPostErrors[keyof AdminLoginApiAuthLoginPostErrors];

export type AdminLoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: AdminLoginResponse;
};

export type AdminLoginApiAuthLoginPostResponse = AdminLoginApiAuthLoginPostResponses[keyof AdminLoginApiAuthLoginPostResponses];

export type RegisterAdminApiAuthRegisterAdminPostData = {
    body: RegisterAdminRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register-admin';
};

export type RegisterAdminApiAuthRegisterAdminPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterAdminApiAuthRegisterAdminPostError = RegisterAdminApiAuthRegisterAdminPostErrors[keyof RegisterAdminApiAuthRegisterAdminPostErrors];

export type RegisterAdminApiAuthRegisterAdminPostResponses = {
    /**
     * Successful Response
     */
    201: RegisterAdminResponse;
};

export type RegisterAdminApiAuthRegisterAdminPostResponse = RegisterAdminApiAuthRegisterAdminPostResponses[keyof RegisterAdminApiAuthRegisterAdminPostResponses];

export type ConfigureSsoProviderApiAuthSsoConfigurePostData = {
    body: ConfigureSsoProviderRequest;
    path?: never;
    query?: never;
    url: '/api/auth/sso/configure';
};

export type ConfigureSsoProviderApiAuthSsoConfigurePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfigureSsoProviderApiAuthSsoConfigurePostError = ConfigureSsoProviderApiAuthSsoConfigurePostErrors[keyof ConfigureSsoProviderApiAuthSsoConfigurePostErrors];

export type ConfigureSsoProviderApiAuthSsoConfigurePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSsoUrlApiAuthSsoUrlGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/sso/url';
};

export type GetSsoUrlApiAuthSsoUrlGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SsoCallbackApiAuthSsoCallbackGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         *
         * Authorization code from SSO provider
         */
        code: string;
        /**
         * State
         *
         * State parameter for CSRF protection
         */
        state?: string;
    };
    url: '/api/auth/sso/callback';
};

export type SsoCallbackApiAuthSsoCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SsoCallbackApiAuthSsoCallbackGetError = SsoCallbackApiAuthSsoCallbackGetErrors[keyof SsoCallbackApiAuthSsoCallbackGetErrors];

export type SsoCallbackApiAuthSsoCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: SsoCallbackResponse;
};

export type SsoCallbackApiAuthSsoCallbackGetResponse = SsoCallbackApiAuthSsoCallbackGetResponses[keyof SsoCallbackApiAuthSsoCallbackGetResponses];

export type IsSsoConfigSetApiAuthSsoIsConfiguredGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/sso/is-configured';
};

export type IsSsoConfigSetApiAuthSsoIsConfiguredGetResponses = {
    /**
     * Successful Response
     */
    200: IsSsoConfigSetResponse;
};

export type IsSsoConfigSetApiAuthSsoIsConfiguredGetResponse = IsSsoConfigSetApiAuthSsoIsConfiguredGetResponses[keyof IsSsoConfigSetApiAuthSsoIsConfiguredGetResponses];

export type RefreshAccessTokenApiAuthRefreshTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh-token';
};

export type RefreshAccessTokenApiAuthRefreshTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshAccessTokenApiAuthRefreshTokenPostError = RefreshAccessTokenApiAuthRefreshTokenPostErrors[keyof RefreshAccessTokenApiAuthRefreshTokenPostErrors];

export type RefreshAccessTokenApiAuthRefreshTokenPostResponses = {
    /**
     * Successful Response
     */
    200: RefreshAccessTokenResponse;
};

export type RefreshAccessTokenApiAuthRefreshTokenPostResponse = RefreshAccessTokenApiAuthRefreshTokenPostResponses[keyof RefreshAccessTokenApiAuthRefreshTokenPostResponses];

export type CreateGroupApiGroupsPostData = {
    body: CreateGroupRequest;
    path?: never;
    query?: never;
    url: '/api/groups/';
};

export type CreateGroupApiGroupsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGroupApiGroupsPostError = CreateGroupApiGroupsPostErrors[keyof CreateGroupApiGroupsPostErrors];

export type CreateGroupApiGroupsPostResponses = {
    /**
     * Successful Response
     */
    201: CreateGroupResponse;
};

export type CreateGroupApiGroupsPostResponse = CreateGroupApiGroupsPostResponses[keyof CreateGroupApiGroupsPostResponses];

export type AddMemberToGroupApiGroupsGroupIdMembersPostData = {
    body: AddMemberToGroupRequest;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/groups/{group_id}/members';
};

export type AddMemberToGroupApiGroupsGroupIdMembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMemberToGroupApiGroupsGroupIdMembersPostError = AddMemberToGroupApiGroupsGroupIdMembersPostErrors[keyof AddMemberToGroupApiGroupsGroupIdMembersPostErrors];

export type AddMemberToGroupApiGroupsGroupIdMembersPostResponses = {
    /**
     * Successful Response
     */
    201: AddMemberToGroupResponse;
};

export type AddMemberToGroupApiGroupsGroupIdMembersPostResponse = AddMemberToGroupApiGroupsGroupIdMembersPostResponses[keyof AddMemberToGroupApiGroupsGroupIdMembersPostResponses];

export type AddOwnerToGroupApiGroupsGroupIdOwnersPostData = {
    body: AddOwnerToGroupRequest;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/groups/{group_id}/owners';
};

export type AddOwnerToGroupApiGroupsGroupIdOwnersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddOwnerToGroupApiGroupsGroupIdOwnersPostError = AddOwnerToGroupApiGroupsGroupIdOwnersPostErrors[keyof AddOwnerToGroupApiGroupsGroupIdOwnersPostErrors];

export type AddOwnerToGroupApiGroupsGroupIdOwnersPostResponses = {
    /**
     * Successful Response
     */
    201: AddOwnerToGroupResponse;
};

export type AddOwnerToGroupApiGroupsGroupIdOwnersPostResponse = AddOwnerToGroupApiGroupsGroupIdOwnersPostResponses[keyof AddOwnerToGroupApiGroupsGroupIdOwnersPostResponses];

export type RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/groups/{group_id}/members/{user_id}';
};

export type RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteError = RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteErrors[keyof RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteErrors];

export type RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: RemoveMemberFromGroupResponse;
};

export type RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteResponse = RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteResponses[keyof RemoveMemberFromGroupApiGroupsGroupIdMembersUserIdDeleteResponses];

export type DeleteGroupApiGroupsGroupIdDeleteData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/groups/{group_id}';
};

export type DeleteGroupApiGroupsGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGroupApiGroupsGroupIdDeleteError = DeleteGroupApiGroupsGroupIdDeleteErrors[keyof DeleteGroupApiGroupsGroupIdDeleteErrors];

export type DeleteGroupApiGroupsGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGroupApiGroupsGroupIdDeleteResponse = DeleteGroupApiGroupsGroupIdDeleteResponses[keyof DeleteGroupApiGroupsGroupIdDeleteResponses];

export type GetGroupApiGroupsGroupIdGetData = {
    body?: never;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/groups/{group_id}';
};

export type GetGroupApiGroupsGroupIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetGroupApiGroupsGroupIdGetError = GetGroupApiGroupsGroupIdGetErrors[keyof GetGroupApiGroupsGroupIdGetErrors];

export type GetGroupApiGroupsGroupIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetGroupResponse;
};

export type GetGroupApiGroupsGroupIdGetResponse = GetGroupApiGroupsGroupIdGetResponses[keyof GetGroupApiGroupsGroupIdGetResponses];

export type UpdateGroupApiGroupsGroupIdPutData = {
    body: UpdateGroupRequest;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/api/groups/{group_id}';
};

export type UpdateGroupApiGroupsGroupIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGroupApiGroupsGroupIdPutError = UpdateGroupApiGroupsGroupIdPutErrors[keyof UpdateGroupApiGroupsGroupIdPutErrors];

export type UpdateGroupApiGroupsGroupIdPutResponses = {
    /**
     * Successful Response
     */
    200: UpdateGroupResponse;
};

export type UpdateGroupApiGroupsGroupIdPutResponse = UpdateGroupApiGroupsGroupIdPutResponses[keyof UpdateGroupApiGroupsGroupIdPutResponses];

export type ListGroupsApiGroupsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Include Personal
         *
         * Include personal groups in results. Set to false to only show shared groups.
         */
        include_personal?: boolean;
    };
    url: '/api/groups';
};

export type ListGroupsApiGroupsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListGroupsApiGroupsGetError = ListGroupsApiGroupsGetErrors[keyof ListGroupsApiGroupsGetErrors];

export type ListGroupsApiGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: ListGroupsResponse;
};

export type ListGroupsApiGroupsGetResponse = ListGroupsApiGroupsGetResponses[keyof ListGroupsApiGroupsGetResponses];

export type ListEventsApiEventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Event Type
         *
         * Filter by event types
         */
        event_type?: Array<string> | null;
        /**
         * Start Date
         *
         * Filter events from this date (inclusive)
         */
        start_date?: string | null;
        /**
         * End Date
         *
         * Filter events until this date (inclusive)
         */
        end_date?: string | null;
    };
    url: '/api/events';
};

export type ListEventsApiEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEventsApiEventsGetError = ListEventsApiEventsGetErrors[keyof ListEventsApiEventsGetErrors];

export type ListEventsApiEventsGetResponses = {
    /**
     * Successful Response
     */
    200: ListEventsResponse;
};

export type ListEventsApiEventsGetResponse = ListEventsApiEventsGetResponses[keyof ListEventsApiEventsGetResponses];
